name: CI

on: push

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
          echo ::set-output name=PACKAGE_VERSION::$(cat package.json | jq -r '.version')
          echo ::set-output name=BRANCH::${GITHUB_REF##*/}
        id: env_vars

      - name: Install Node.js ${{ steps.env_vars.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Security Audit
        run: yarn audit || true

      - name: Outdated Packages
        run: yarn outdated || true

      - name: Coding Standards
        run: yarn lint

      - name: Test
        run: yarn test:coverage

      - name: Type
        run: yarn type

      - name: Build
        run: yarn build

      - name: Package Public Folder
        if: github.ref == 'refs/heads/main'
        run: yarn predeploy

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: public

      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Pre-release
        if: github.ref != 'refs/heads/main'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.env_vars.outputs.PACKAGE_VERSION }}
          release_name: ${{ steps.env_vars.outputs.PACKAGE_VERSION }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
          prerelease: true

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.env_vars.outputs.PACKAGE_VERSION }}
          release_name: ${{ steps.env_vars.outputs.PACKAGE_VERSION }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Publish to Registry
        run: |
          pkg_version=${{ steps.env_vars.outputs.PACKAGE_VERSION }}
          branch=${{ steps.env_vars.outputs.BRANCH }}

          if [[ $branch != "main" ]]; then
            yarn version --new-version "$pkg_version-beta$GITHUB_RUN_NUMBER" --no-git-tag-version
            yarn publish --tag beta --access public
          else
            yarn publish --access public
          fi
